image: gcc

stages:
  - test
  - build

build:
  stage: build
  script: 
    - gcc --version
    - make build
  artifacts:
    paths:
      - a_release.exe

test:
  stage: test
  script:
    - gcc --version
    - make test