name: build

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install gcovr
      run: |
        sudo apt-get -y install gcovr
    - name: Test
      run: |
        gcc --version
        make test
    - uses: codecov/codecov-action@v2

  build_windows:
    runs-on: windows-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.8
    - name: Upgrade pip and
      run: python -m pip install --upgrade pip
    - name: Install gcovr
      run: pip install gcovr
    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - name: Build
      run: |
        gcc --version
        make build
      shell: cmd
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: aes.exe
        path: aes.exe

  build_ubuntu:
    strategy:
      matrix:
        tag: [focal]
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Install gcovr
      run: |
        sudo apt-get -y install gcovr
    - name: Build
      run: |
        gcc --version
        make build
        cp aes.exe aes_ubuntu_${{ matrix.tag }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: aes_ubuntu_${{ matrix.tag }}
        path: aes_ubuntu_${{ matrix.tag }}
